### ISSUE TITLE
Mapping not accessible in next state

### ISSUE THREAD

**Issue by bitbart** [AngeloFerrando/Solvent#31]
Check the regression test mapping1.sol:
```
contract Mapping1 {
    mapping (address => int) m

    function foo() {
        m[msg.sender] = m[msg.sender] + 1
    }
}  
property live1 {
    Forall xa
      [
        true 
          -> 
        Exists tx [1, xa]
        [
          (app_tx_st.m[xa] == st.m[xa] + 1)
        ]
      ]
}
```
This gives a compilation error:
```
python3 ../../main.py mapping1.sol 100 2 true
Traceback (most recent call last):
  File "/home/bart/progs/solvent/contracts/regression/./out/outputTrace.py", line 207, in <module>
    queries['live1'] = [[p_live1_1(i)] for i in range(1, N+1)]
  File "/home/bart/progs/solvent/contracts/regression/./out/outputTrace.py", line 207, in <listcomp>
    queries['live1'] = [[p_live1_1(i)] for i in range(1, N+1)]
  File "/home/bart/progs/solvent/contracts/regression/./out/outputTrace.py", line 203, in p_live1_1
    Not(And([Or(j != xa_q, app_tx_m_q == (m[i][j]+1)) for j in range(A+1)]))
  File "/home/bart/progs/solvent/contracts/regression/./out/outputTrace.py", line 203, in <listcomp>
    Not(And([Or(j != xa_q, app_tx_m_q == (m[i][j]+1)) for j in range(A+1)]))
NameError: name 'app_tx_m_q' is not defined
make: *** [Makefile:23: compile] Error 1
```

**Comment by AngeloFerrando** [comment]
Commit 41f357d fix this issue
